---
- name: Gather instance facts
  setup:

- name: Install python-apt package
  apt:
    name: python-apt
    state: present
    update_cache: yes

- name: Gather package facts
  package_facts:
    manager: auto

- name: Include tasks for network setups using ifupdown
  include_tasks: "setup_interfaces.yml"
  when:
    - "'netplan.io' not in ansible_facts.packages"

- name: Include tasks for network setups using netplan.io
  include_tasks: "setup_netplan.yml"
  when:
    - "'netplan.io' in ansible_facts.packages"
